[workspace]
[package]
version = "0.1.0"
name = "sp1-vectorx-primitives"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
dotenv = "0.15.0"
sha2 = { version = "0.10.8", default-features = false }
anyhow = "1.0.68"
clap = "4.4.9"
ed25519-dalek = "2.1.1"
codec = { package = "parity-scale-codec", version = "3", default-features = false }
hex = "0.4.3"
