[workspace]
members = [
  "cli",
  "core",
  "derive",
  "eval",
  "helper",
  "primitives",
  "prover",
  "recursion/circuit",
  "recursion/compiler",
  "recursion/core",
  "recursion/gnark-ffi",
  "recursion/program",
  "sdk",
  "zkvm/*",
]
exclude = ["examples/target"]
resolver = "2"
