[workspace]
[package]
version = "0.1.0"
name = "sp1-vectorx-script"
edition = "2021"

[[bin]]
name = "rotate"
path = "src/bin/rotate.rs"

[[bin]]
name = "header_range"
path = "src/bin/header_range.rs"

[dependencies]
sp1-vectorx-primitives = { path = "../primitives" }
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git", branch = "dev" }
ed25519-consensus = { version = "2", default-features = false }
rand = "0.8"
env_logger = { version = "0.9.0", default-features = false }
hex = "0.4.3"
itertools = "0.10.5"
ff = { package = "ff_ce", version = "0.11", features = ["derive"] }
log = { version = "0.4.14", default-features = false }
num = { version = "0.4", features = ["rand"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.86"
tokio = { version = "1.2.0", features = ["full"] }
reqwest = "0.11.20"
ethers = { version = "2.0.10", features = ["ws"] }
sha256 = "1.4.0"
primitive-types = "0.12.1"

dotenv = "0.15.0"
avail-subxt = { git = "https://github.com/availproject/avail.git", tag = "v2.0.0.0-rc4" }
subxt = "0.34"
sp-core = { git = "https://github.com/availproject/polkadot-sdk.git", tag = "polkadot-1.7.1-patch-2", default-features = false }
sha2 = { version = "0.10.8", default-features = false }
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
    "full",
    "bit-vec",
] }
alloy-sol-types = "0.4.2"
alloy-primitives = "0.4.2"
anyhow = "1.0.68"
clap = "4.4.9"
futures = "0.3.30"
async-trait = "0.1.77"
ed25519-dalek = "2.1.1"

[build-dependencies]
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git", branch = "dev" }
