[package]
version = "0.1.0"
name = "sp1-vectorx-program"
edition = "2021"

[dependencies]
sp1-vector-primitives.workspace = true
alloy-sol-types.workspace = true
sp1-zkvm = { version = "4.0.0-rc.8" }
