[book]
authors = ["SP1 Vector Team"]
language = "en"
multilingual = false
src = "src"
title = "SP1 Vector Documentation"

[output.html]
git-repository-url = "https://github.com/yourusername/sp1-vector"
git-repository-icon = "fa-github"
