name: "CI"
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    branches:
      - "**"

jobs:
  test:
    name: CI Test Suite
    runs-on: buildjet-32vcpu-ubuntu-2204
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    strategy:
      matrix:
        project:
          - primitives
          - rotate
          - script
          - header-range
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: rust-cache
        uses: buildjet/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            ~/.rustup/
          key: test-rust-nightly-2024-02-22-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: rust-nightly-2024-02-22-
      - name: Install nightly toolchain
        id: rustc-toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2024-02-22
          override: true
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --features "ci"
          working-directory: sp1-vectorx/${{ matrix.project }}
        env:
          RUST_LOG: info
          RUST_BACKTRACE: 1

  lints:
    name: Formatting & Clippy
    runs-on: buildjet-32vcpu-ubuntu-2204
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    strategy:
      matrix:
        project:
          - primitives
          - rotate
          - script
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: rust-cache
        uses: buildjet/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            ~/.rustup/
          key: clippy-rust-nightly-2024-02-22-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: rust-nightly-2024-02-22-
      - name: Install nightly toolchain
        id: rustc-toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2024-02-22
          override: true
          components: rustfmt, clippy
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
          working-directory: sp1-vectorx/${{ matrix.project }}
        env:
          CARGO_INCREMENTAL: 1
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets -- -D warnings -A incomplete-features
          working-directory: sp1-vectorx/${{ matrix.project }}
        env:
          CARGO_INCREMENTAL: 1